### ISSUE TITLE
Cannot convert parameter to block

### ISSUE THREAD

**Issue by alessaba** [jsbain/objc_hacks#2]
If i run the script objcblock and nsblock it says in the line where you call the function: cannot convert parameter to block
I'm on ipad air 2 (64bit)

**Comment by jsbain** [comment]
which line?  can you post your call?

fyi this module is more or less obsolete in the new beta, since omz has added an ObjCBlock which is easier to use, and is more likely to work on 64 bit!

**Comment by alessaba** [comment]
I know, but i wanna try it :-)

![image](https://cloud.githubusercontent.com/assets/2400384/9257419/c1269992-41f5-11e5-85f6-e05f66cf00b2.png)
